name: Build AppBundle & ABI (w/ split-debug-info)

on:	
  workflow_dispatch:
    inputs:
      java_version:
        description: 'Java version'     
        required: true
        default: '17'
      java_distribution:
        description: 'Java distribution'     
        required: true
        default: 'temurin'

env:	
  KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}	
  ALIAS_NAME: ${{ secrets.ALIAS_NAME }}	
  ALIAS_PASS: ${{ secrets.ALIAS_PASS }}	

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ github.event.inputs.java_distribution || 'temurin' }}
        java-version: ${{ github.event.inputs.java_version || '17' }}

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Override Dependencies
      run: |
        sudo add-apt-repository ppa:rmescandon/yq -y
        sudo apt update
        sudo apt install yq -y
        
        # Add a temp fix for dio
        # yq w -i pubspec.yaml dependencies.dio 4.0.0-beta5

    - name: Flutter Build Pre-Checks Phase 1
      run: |
        flutter doctor
        flutter pub get
  
    - name: Flutter Build Pre-Checks Phase 2
      run: |
        flutter packages pub run build_runner build --delete-conflicting-outputs

    - name: Flutter Test
      continue-on-error: true
      run: |
        flutter test
    
    - name: Flutter Build ABI
      continue-on-error: true
      run: |
        flutter build apk --release --target-platform=android-arm64 --dart-define=IS_GOOGLEPLAY=false --split-debug-info=

    - uses: actions/upload-artifact@v4
      name: Upload Variants
      with:
        name: app-release
        path: build/app/outputs/apk/release/*.apk
